### ISSUE TITLE
Headers on iOS are displaying too large

### ISSUE THREAD

**Issue by pixologist** [ceciliamay/obsidianmd-theme-primary#1]
First off, beautiful theme, the iconography and use of color between light are dark modes are brilliant and make obsidian even more of a joy to use. There is however one display bug when using the theme on iOS which affects usability; headers (#, ## & ###) are displaying too large at the moment, effectively filling the entire screen/editor region.
![headersIssue](https://user-images.githubusercontent.com/20881754/139734597-819bae08-819e-4206-9a1b-007b0e1a9ab3.PNG)

Thank you!

**Comment by lizsugar** [comment]
Headers display like that on android version too

**Comment by ceciliamay** [comment]
Thank you to you both for flagging this issue!! 🙏

This has now been fixed on [Release v.0.2.0](https://github.com/ceciliamay/obsidianmd-theme-primary/releases/tag/v0.2.0) along with other mobile-optimized styling for both phones and tablets!! 🎉 

Please update your themes and definitely let me know if you experience any other issues 😄
