### ISSUE TITLE
Bug: New insiders release breaks Primary's font

### ISSUE THREAD

**Issue by HEmile** [ceciliamay/obsidianmd-theme-primary#101]
In the latest inside release, Obsidian added this feature:
> - You can now set the font for the interface and the editor directly under appearance settings. Note that some themes may override this font setting.

Unfortunately it seems like Primary's font does not seem to apply anymore _everywhere_. In the editor, it works, but the callout font is different, and the file browser looks different too:
<img width="1627" alt="image" src="https://user-images.githubusercontent.com/1289165/160477096-52a46ad7-d341-4046-8467-0909bbcb0521.png">

Reading view seems to work completely.

**Comment by miharekar** [comment]
There's been some discussion around this [on the discord](https://discordapp.com/channels/686053708261228577/716028884885307432/958112338345590804)

**Comment by ceciliamay** [comment]
((Partially)) fixed in [v.1.4.4](https://github.com/ceciliamay/obsidianmd-theme-primary/releases/tag/v.1.4.4)! I'll do one more final update once Licat pushes the proper variable update. Thank you so much for reporting, and thank you for the link @miharekar !!!

**Comment by ceciliamay** [comment]
Licat just pushed another Insider's update: This should be fixed again!

**Comment by HEmile** [comment]
Latest insider somehow broke it again lol

**Comment by ceciliamay** [comment]
wait that has to be april fools @HEmile (i've been fooled many times today 😭 i don't know what to believe anymore HAHAHAHA) - because i don't have any issues 😭 can you try reinstalling installing the theme?

**Comment by HEmile** [comment]
hahaha I'm afraid this wasn't april fools @ceciliamay , doesn't work after reinstalling either.

**Comment by ceciliamay** [comment]
@HEmile I checked with Eleanor on Discord, Primary seems to be using Karla on default on her end too (no Style Settings:
![image](https://user-images.githubusercontent.com/90643719/161407249-79812e57-3b6d-49ce-87d3-0e872206d6ad.png)

Here's mine with all plugins turned off:
![image](https://user-images.githubusercontent.com/90643719/161407264-c7f8c9a1-b32e-492b-b1d0-9f7222fe938f.png)

The only reason I can think of so far of why it wouldn't be using Karla on your end is if you are not on v.0.14.5 or that a snippet or Style Setting is overriding it 🤔

**Comment by HEmile** [comment]
Haha euh... I think I fixed it by disabling a snippet and restarting!
