### ISSUE TITLE
[Suggestion] Don't hide icons with Mini Floating Side Docks

### ISSUE THREAD

**Issue by Mara-Li** [ceciliamay/obsidianmd-theme-primary#105]
Using this option hide the icons from left (sidebar). It will be possible to add an option to have it for this option ? 
![image](https://user-images.githubusercontent.com/30244939/161032755-431faef9-42f9-4950-8f88-36d9563a026f.png)

Also, it will be cool if we can move the "hover" option for the side docks. I prefer to have it to the bottom than the middle.

Thanks for this wonderfull theme !

**Comment by ceciliamay** [comment]
Hello there @Mara-Li !! I apologize but I don't think I quite understand what you are suggesting?
Are you asking for the Mini Floating Side Docks to not have lower opacity when sidebar is open?
Sorry for misunderstanding!

**Comment by Mara-Li** [comment]
Sorry ! 
I mean, the icons there are on the sidebar, as that (in "normal" mode) : 
![image](https://user-images.githubusercontent.com/30244939/161095703-0fcda5b1-dfe3-4068-b356-b30c15b016ec.png)

**Comment by ceciliamay** [comment]
Hello!! I've fixed this in the added this update: https://github.com/ceciliamay/obsidianmd-theme-primary/releases/tag/v.1.4.8
Please update your theme!!

I forgot that I added this early in. Thank you so much for suggesting this!!
