### ISSUE TITLE
Right or left aligned images dont fit box

### ISSUE THREAD

**Issue by Pummelfisch** [ceciliamay/obsidianmd-theme-primary#108]
If I use inlR or inlL to align images to the left or right the box that makes images *round* does'nt fit arround the image. For clarification i embeded the images like `![image.png|inlR|150]`
In the attachement you can see a left aligned image, a centered one (here everything works as expected) and i right aligned one. You can see the boxes.

![Imagebox bug](https://user-images.githubusercontent.com/67376951/161253699-b53e8adb-f061-42ed-8638-9f1541d47107.png)

**Comment by ceciliamay** [comment]
I don't think `inlR` or `inlL` is an Obsidian-native feature? (Correct me if I am wrong) - If it isn't an Obsidian-native feature I unfortunately do not support it. Moving forward with this assumption I think you might be using a snippet - or you used a feature that was in another theme. 

Using those syntaxes on my end just resulted to left aligned images - even in the Sandbox vault:
![image](https://user-images.githubusercontent.com/90643719/161257675-85532a7a-ed4c-4a7c-b5df-c7210d9219a1.png)

Please take a look at your snippet!

**Comment by Pummelfisch** [comment]
Ahh yes it was hidden in a css-class i didnt ad my eyes on. Sorry for the misleading inquiry.
