### ISSUE TITLE
Can't edit header size - Live preview mode

### ISSUE THREAD

**Issue by gabb0z** [ceciliamay/obsidianmd-theme-primary#109]
I can't edit the size of header in the live preview mode

live preview mode:
<img width="720" alt="image" src="https://user-images.githubusercontent.com/47632191/161254799-04b97300-545a-40de-8771-1e35a9d38efa.png">

reading mode:

<img width="646" alt="image" src="https://user-images.githubusercontent.com/47632191/161254920-2b9dd770-dd62-4408-b093-fa47203da898.png">

Setting changed:
<img width="870" alt="image" src="https://user-images.githubusercontent.com/47632191/161255012-f1be7767-5c49-461b-a9e5-f014b6bd286e.png">

any idea for a workaround here?

**Comment by ceciliamay** [comment]
Hello there @gabb0z ! I can't seem to replicate this issue. It's working fine on my end:
![tutorial-issue](https://user-images.githubusercontent.com/90643719/161258853-81bc5730-433e-4c5b-8046-95eb04cf0f17.gif)

Can you try reinstalling the theme? Restarting Style Settings? or Restarting Obsidian? Let me know if any of these work!

**Comment by gabb0z** [comment]
Hi Cecilia! Uninstalling the theme, and restarting obsidian did the trick! thanks for your time :) have a nice weekend!

**Comment by ceciliamay** [comment]
YAAY!!! have a nice weekend too~ 😎
