### ISSUE TITLE
[enhancement] Configure alternate colors for external links in settings

### ISSUE THREAD

**Issue by al3x** [ceciliamay/obsidianmd-theme-primary#113]
I'd like to be able to pick a different color for external links (that is, links to websites, not links within my vault). Right now, external links have a handy icon next to them, but I still find color easier/faster to differentiate. Exposing this setting via the Style Settings plugin would be ideal.

Thank you for a great theme!

**Comment by ceciliamay** [comment]
This has been added in [v.1.4.7](https://github.com/ceciliamay/obsidianmd-theme-primary/releases/tag/v.1.4.7) - please update your themes! @al3x thank you so much for support!!

**Comment by morningfin** [comment]
Is this only be used through <progress value="10" max="100"></progress> ? Are there any shortcuts for it?

**Comment by ceciliamay** [comment]
@morningfin I am not sure what you are specifically asking but my guess is:
to change colors for external links you must download the Style Settings plugin (by mgmeyers) and then in the Plugin Options go to Style Settings -> Primary Theme Settings -> Note -> Links -> External Links. There are no shortcuts/hotkeys for this one as this is only enabled through the Style Settings!

Hope this helps and let me know if you have other questions!
