### ISSUE TITLE
Font customizations are not applied to dataview blocks

### ISSUE THREAD

**Issue by dsent** [ceciliamay/obsidianmd-theme-primary#119]
I've set up all my fonts through Style Settings to be `"Inter", -apple-system, BlinkMacSystemFont, Helvetica, Arial, sans-serif`:
![image](https://user-images.githubusercontent.com/8774536/163563336-3e2104f5-4dfe-4d02-974e-9d2fa4a015c5.png)

However, for dataview blocks (and, possibly, other types of blocks?) the font is still the default Karla.

See the computed style for reference:
![image](https://user-images.githubusercontent.com/8774536/163563056-08f59161-219b-40bc-a9e5-b9a9a8ecfc40.png)

And the result is:
![image](https://user-images.githubusercontent.com/8774536/163562877-091ba020-5b93-443e-9971-558e237376ab.png)

For anyone interested, this is the rendered dataview query for the latest modified notes:
```
```dataview
LIST 
WHERE date(today) - file.mtime
WHERE file.name != this.file.name
SORT file.mtime DESC
LIMIT 25
```

**Comment by ceciliamay** [comment]
This has been fixed in [v.1.4.7](https://github.com/ceciliamay/obsidianmd-theme-primary/releases/tag/v.1.4.7) - please update your theme! thank you so much - as always - for reporting!!

**Comment by dsent** [comment]
Looks perfectly fine now, thank you!
