### ISSUE TITLE
Old primary themes checkbox design

### ISSUE THREAD

**Issue by AdityaBanik** [ceciliamay/obsidianmd-theme-primary#120]
I really loved the old primary themes checkbox design implementation .

I would really appreciate if u keep that in the updated theme as well.

**Comment by 702573n** [comment]
Please implement an option to change the checkbox style with "Style Settings" Plugin.

Old / New / Round / Rectangle

**Comment by ceciliamay** [comment]
Hello @702573n and @AdityaBanik !! I've added this option in the recent update: https://github.com/ceciliamay/obsidianmd-theme-primary/releases/tag/v.1.4.8

Please update your theme!! Thank you so much for your patience 🙏
