### ISSUE TITLE
Numbers are not correctly aligned in the `Backlinks in Document`

### ISSUE THREAD

**Issue by oxdc** [ceciliamay/obsidianmd-theme-primary#122]
![1](https://user-images.githubusercontent.com/29519076/163760689-65db2267-2eca-48c1-a715-7a849452cc2d.png)

I'm using the latest insider build (v0.14.6).

**Comment by spcbfr** [comment]
Same issue in v0.14.6 (now a public build)

**Comment by ceciliamay** [comment]
This has been fixed in [v.1.4.7](https://github.com/ceciliamay/obsidianmd-theme-primary/releases/tag/v.1.4.7) - please update your themes!
