### ISSUE TITLE
Customization of Highlighted text not working

### ISSUE THREAD

**Issue by Gattomarino** [ceciliamay/obsidianmd-theme-primary#124]
Hi! This theme is a real work of art. However I found a minor bug, I checked it both on Mac and Win. It could be a bug in the Style Settings plugin, I'm not sure:

Style Settings > Note > Highlight > Custom Highlight > Highlight-only Text Color: when I change the color of the text (not the background: that one works) and save it, nothing happens, neither in Light nor Dark mode.

**Comment by badjerphoenix** [comment]
In addition to the devices mentioned above I have also tested on Android (phone) & it does not work from there either

**Comment by ceciliamay** [comment]
Hey @Gattomarino and @badjerphoenix !! This has been fixed in [v.1.4.7](https://github.com/ceciliamay/obsidianmd-theme-primary/releases/tag/v.1.4.7) - please update your themes!
