### ISSUE TITLE
Progress bar during plugin updates does not appear

### ISSUE THREAD

**Issue by swehba** [ceciliamay/obsidianmd-theme-primary#129]
When using the Primary theme, the progress bar that usually displays when updating plugins does not appear. This makes it difficult to know if the update is running and when it completes.

**Comment by ceciliamay** [comment]
Hello @swehba !! I've fixed this in the recent update: https://github.com/ceciliamay/obsidianmd-theme-primary/releases/tag/v.1.4.8
Please update your theme!! Thank you so much for reporting this issue 🙏
