### ISSUE TITLE
Hiding tags is not possible with a css snippet

### ISSUE THREAD

**Issue by Signynt** [ceciliamay/obsidianmd-theme-primary#15]
I prefer to have my tags hidden in my notes, so I use a little css snippet to hide them:

```
.markdown-preview-view .tag {
    display: none;
}
```

This snippet works great in most themes, but unfortunately does not have any affect in Primary.
It would be great if this could be fixed in this pleasant and fun theme!

**Comment by ceciliamay** [comment]
Hey there!! Thanks for reporting this!! I checked it out and looks like it needed the classes `.theme-light` and `.theme-dark` at the start. Here's the snippet that I checked and worked:

```
.theme-light .markdown-preview-view .tag,
.theme-dark .markdown-preview-view .tag {
    display: none;
}
```

Let me know if issues still persist!! Thank you so so much, I'm so glad you're enjoying the theme!! ✨❤

**Comment by Signynt** [comment]
That's good to know, it fixed the issue, thanks!
