### ISSUE TITLE
v0.16.0 compatibility

### ISSUE THREAD

**Issue by miharekar** [ceciliamay/obsidianmd-theme-primary#154]
There were a ton of changes and ATM Primary doesn't look great 😬 

<img width="641" alt="CleanShot 2022-08-30 at 12 45 31" src="https://user-images.githubusercontent.com/986645/187417418-68332655-c44e-494a-9529-e5043bd3fe96.png">

The biggest issue is that scrolling simply doesn't work in settings.

**Comment by pastordan** [comment]
Scrolling seems to work for me on notes, but not in modals, which is...not great. The other issue I've noticed is that bullets are wonky:
<img width="94" alt="Screen Shot 2022-08-30 at 8 08 32 AM" src="https://user-images.githubusercontent.com/20197184/187444900-44ec573f-715e-467e-8c84-1397eb4de0ac.png">

**Comment by Lisandra-dev** [comment]
Primary is totally broken by the 0.16 update. A lot of things is totally unusable (i.e. scrolling)

**Comment by pastordan** [comment]
Here are some CSS patches while Cecilia works out the kinks:

/*16.0 broke a lot of shit */
.markdown-source-view.mod-cm6 .callout {
padding:  0;
border:  1px solid transparent;
border-radius: 0;
transition: var --duration-superfast;
}

.md-bullet-color-muted.theme-light span.cm-formatting.cm-formatting-list,
.md-bullet-color-muted.theme-light span.list-bullet,
.md-bullet-color-muted.theme-light li::marker,
.md-bullet-color-muted.theme-dark span.cm-formatting.cm-formatting-list,
.md-bullet-color-muted.theme-dark span.list-bullet,
.md-bullet-color-muted.theme-dark li::marker,
markdown-rendered.list-bullet, list-bullet {
color: var(--background-secondary);
}

svg.svg-icon.lucide-edit-3 path:first-of-type {
color:  var(--callout-title-background);
}

.workspace-ribbon.mod-left:before {
padding-bottom: 19px;
}

div.side-dock-actions {margin-top: 19px;
}

.mod-left-split .workspace-tab-header-container-inner, .mod-right-split
.workspace-tab-header-container-inner {
gap: 10px;
}

div.workspace-tab-header {
padding-right: 5px !important;
padding-left: 5px !important;
}

I'm not smart enough to figure out how to fix the scrolling issue, though.

**Comment by Lisandra-dev** [comment]
The broken scroll is because of : 
`.modal {overflow-y: hidden}`

So, to fix it :
```
.modal {
    overflow-y: auto !important;
}
```

Also, for settings background : 

```css
.theme-dark .modal .modal-content .vertical-tab-header,
.theme-dark .modal .modal-content .vertical-tab-content-container .vertical-tab-content {
    background-color: var(--background-secondary) !important;
}
```

**Comment by pastordan** [comment]
That didn't work for me, but this did:

.modal.mod-settings .modal-content {
    overflow-y: scroll !important;
}

Thanks for the hint!

**Comment by Lisandra-dev** [comment]
Seems broken because when I scroll to down, I can't see any option... We must to wait @ceciliamay an update/fix for 0.16 :/

**Comment by miharekar** [comment]
Here's a [theme migration guide](https://forum.obsidian.md/t/0-16-0-theme-migration-guide/42537) that should help.

**Comment by aquatix** [comment]
Version 1.0 of Obsidian just was released, and I'm now on the default theme instead of the goodness that is Primary. Hopefully we can fix compatibility soon :)

Let me/us know if we as the community can help out, as I am aware that there has been significant changes going to the new engine.

**Comment by miharekar** [comment]
Closing because 0.16 got rebranded as 1.0 and the discussion is continued in #164
