### ISSUE TITLE
issue: icon for removal of mobile toolbar missing

### ISSUE THREAD

**Issue by brimwats** [ceciliamay/obsidianmd-theme-primary#16]
![Screenshot_20211115-174546_Obsidian](https://user-images.githubusercontent.com/49103046/141880786-225a0b6f-3a15-4c21-a858-71e9817fa0d2.jpg)

you can see them missing here

![Screenshot_20211115-174732_Obsidian](https://user-images.githubusercontent.com/49103046/141880828-9c57e8f2-22ec-4c0b-badb-dad761d265fa.jpg)

**Comment by ceciliamay** [comment]
Thank you so much for reporting this issue!! I just fixed it and pushed an update — [Release v.0.2.4](https://github.com/ceciliamay/obsidianmd-theme-primary/releases/tag/v0.2.4)! 🎉 Here's how it's looking at my end:

![image](https://user-images.githubusercontent.com/90643719/141997748-b2178691-7b92-4d6a-becf-91e17a814809.png)
