### ISSUE TITLE
Which fonts are used in this theme?

### ISSUE THREAD

**Issue by vp275** [ceciliamay/obsidianmd-theme-primary#162]
Hi! Can you tell me the name of all the fonts that are used in this theme ? They're brilliant!!!

**Comment by ceciliamay** [comment]
Hello @vp275 !! 

The default font is [Karla](https://fonts.google.com/specimen/Karla) . For code parts, [Cascadia Code](https://github.com/microsoft/cascadia-code) is used.

When Style Settings plugin is downloaded you have access to [Inter](https://github.com/rsms/inter), [Lora](https://fonts.google.com/specimen/Lora), [Quicksand](https://fonts.google.com/specimen/Quicksand), and [Roboto Slab](https://fonts.google.com/specimen/Roboto+Slab). 

Hope this helps~! Thank you so much for the kind words ❤️
