### ISSUE TITLE
Issue finding the theme in Obsidian app

### ISSUE THREAD

**Issue by EmranMR** [ceciliamay/obsidianmd-theme-primary#178]
Hi,
I am not sure if I am doing anything wrong or if this theme is only available to get installed manually. But I can not find the Primary theme in the theme marketplace in the app...

Could anyone guide me on how to successfully install the theme in the iOS and the MacOS?

thanks

**Comment by EmranMR** [comment]
Ah just saw the forum that it is not supported in the new Obsidian for time being.

**Comment by Tejeev** [comment]
@EmranMR, what forum are you referring to?

**Comment by aka-mj** [comment]
https://forum.obsidian.md/t/primary-theme/26687
https://github.com/ceciliamay/obsidianmd-theme-primary/issues/166

**Comment by ceciliamay** [comment]
hey folks! Primary - newly rebuilt and refreshed - is now available publicly in the Obsidian Theme Store! You can read the full release notes here: https://github.com/primary-theme/obsidian/releases/tag/v.2.7.0

[How to Install](https://github.com/primary-theme/obsidian?tab=readme-ov-file#install-official-release)

![Image](https://github.com/user-attachments/assets/d7eceb90-c08c-4558-b9f6-acbf2b2bbb5d)

![Image](https://github.com/user-attachments/assets/e6079027-1794-4956-a7f8-a795fe251d85)

**Comment by Tejeev** [comment]
Just wanted to say thank you very very much.  Really appreciate you making this available and maintaining it! :)

**Comment by ceciliamay** [comment]
thank you for taking the time for such kind words @Tejeev !! happy to serve <3
