### ISSUE TITLE
Selecting text within a code-block in edit-mode doesn't highlight.

### ISSUE THREAD

**Issue by jackbodine** [ceciliamay/obsidianmd-theme-primary#18]
![highlight](https://user-images.githubusercontent.com/25469979/142080464-e4a45a3e-8fea-4fa5-adeb-4df538816d48.gif)

When selecting text in a code block, no indicator of whats been highlighted appears. This only happens in edit mode. The cursor also seems to disappear/stop blinking once any text is highlighted.

The text is still selected, and can be copied/pasted/etc, there just isn't any indicator.

**Comment by jackbodine** [comment]
I forgot to mention, I have the [Editor Syntax Highlight](https://github.com/deathau/cm-editor-syntax-highlight-obsidian) plugin installed and activated (seen in the .gif), but the issue persists even with the plug-in turned off.

**Comment by ceciliamay** [comment]
Thank you so much for reporting this!!! I have quickly fixed this in [Release v.0.2.5](https://github.com/ceciliamay/obsidianmd-theme-primary/releases/tag/v0.2.5) 🎉
