### ISSUE TITLE
Obsidian comments and Mathjax delimiters have low contrast in dark mode

### ISSUE THREAD

**Issue by SkepticMystic** [ceciliamay/obsidianmd-theme-primary#2]
The first line in the image is `%% Comment %%`, the second line is surrounded by `$ ... $`, but it's really difficult to see.
![image](https://user-images.githubusercontent.com/70717676/139799485-3c87aa22-4f9e-4b09-bc70-2a96acfededc.png)

**Comment by ceciliamay** [comment]
This has been fixed in [Release v.0.1.1](https://github.com/ceciliamay/obsidianmd-theme-primary/releases/tag/v0.1.1)! 🎉
