### ISSUE TITLE
FR: Style Settings

### ISSUE THREAD

**Issue by brimwats1** [ceciliamay/obsidianmd-theme-primary#23]
I would love for this theme to have integrations with the [style settings](https://github.com/mgmeyers/obsidian-style-settings) plugin—specifically I'm looking for the ability to customize heading fonts/colors and use different fonts in different aspects of the theme. 

California Coast uses it most comprehensively probably: [mgmeyers/obsidian-california-coast-theme: A minimalist obsidian theme inspired by macOS Big Sur](https://github.com/mgmeyers/obsidian-california-coast-theme)

**Comment by ceciliamay** [comment]
I'm working on it 😉 I'm currently cleaning things!

**Comment by dsent** [comment]
Would be one way of addressing #36, btw.

**Comment by ceciliamay** [comment]
[Style Settings is now available for Primary on v.1.2](https://github.com/ceciliamay/obsidianmd-theme-primary/releases/tag/v.1.2.0)!! Please update your themes 😄 More settings in the coming weeks.
