### ISSUE TITLE
Follow link prompt on mobile disappears under the gutter

### ISSUE THREAD

**Issue by Signynt** [ceciliamay/obsidianmd-theme-primary#24]
Making a link on the left of a line, near the gutter, causes the “Follow link” prompt to overlap with it, and disappear underneath it. 
Just a minor visual bug!
![68E6DDDE-0F68-49F4-96AA-2BE10E9D0CCE](https://user-images.githubusercontent.com/67801159/143425746-83c71395-2d2f-4a66-a430-799feaf105fd.png)

**Comment by ceciliamay** [comment]
Hello there @Signynt !! I was wondering if this still occurs?

**Comment by Signynt** [comment]
Hey @ceciliamay, I just checked, it isn't occurring anymore!
