### ISSUE TITLE
Cursor disappears on mobile when in an empty line

### ISSUE THREAD

**Issue by Signynt** [ceciliamay/obsidianmd-theme-primary#25]
https://user-images.githubusercontent.com/67801159/143452420-e97e9489-423e-499c-a91a-b129858e0329.mp4

When in an empty line the cursor disappears, as seen in the video. This happens on my android phone, but not on my iPad.

**Comment by ceciliamay** [comment]
Hmmm... I've tested it using an android phone too (specifically Samsung A30) - I checked on my end, and it seems to be working fine. No carets with invisibility powers. I wonder if anyone else has this issue? I'll let this sit here for a while to see if this still occurs.

**Comment by ceciliamay** [comment]
Hello @Signynt !! Does this still occur?

**Comment by Signynt** [comment]
Hey @ceciliamay ! 
Yeah, unfortunately this is still an issue :c

**Comment by ceciliamay** [comment]
Hey!! I tried fixing this by adding color to the caret cursor. It's now at v.1.0. Please update your theme and let me know how it goes! [Here's the changelog.](https://github.com/ceciliamay/obsidianmd-theme-primary/releases/tag/v.1.0.0)
