### ISSUE TITLE
can't show paragraph breaks within a quote block

### ISSUE THREAD

**Issue by toddz262** [ceciliamay/obsidianmd-theme-primary#28]
The theme is lovely - I really like it!

I've noticed it doesn't seem to want to display paragraph breaks within a quote block.
The usual solution here doesn't work for me in Primary: https://forum.obsidian.md/t/preserve-newline-in-quote-block/571/6

**Comment by huyz** [comment]
Yes I have the same problem, which means I have to go back to the system default theme as I use quote blocks a lot.

My understanding is https://forum.obsidian.md/t/preserve-newline-in-quote-block/571/6 is not relevant.  That is for treating single newlines as paragraph breaks.

The problem with the Primary theme in Preview mode is that 2 consecutive newlines should always be considered a paragraph break by the Markdown spec.

**Comment by toddz262** [comment]
Thanks for clarifying, huyz!

**Comment by ceciliamay** [comment]
Please update your theme! I tried fixing this issue with v.1.0. Please check it out! [Here's the changelog.](https://github.com/ceciliamay/obsidianmd-theme-primary/releases/tag/v.1.0.0)

**Comment by toddz262** [comment]
Looks fixed indeed -- thank you!
