### ISSUE TITLE
Image not resizing 

### ISSUE THREAD

**Issue by liberrenaud** [ceciliamay/obsidianmd-theme-primary#29]
Hey Cecilia,

Gorgeous theme, congrats!
I noticed that when wanted to resize image size (ie. ![[image.png**|2000**]]) - in preview mode, it does not "apply" the resizing when the theme is being used.

All the best,
Renaud

**Comment by ceciliamay** [comment]
This should be fixed in the new v.1.0 mega update! Please update your theme and let me know how it goes. [Here's the changelog.](https://github.com/ceciliamay/obsidianmd-theme-primary/releases/tag/v.1.0.0) ✨
