### ISSUE TITLE
wrong icon on horizontal split 

### ISSUE THREAD

**Issue by seatrout** [ceciliamay/obsidianmd-theme-primary#30]
This is a tiny fix if ever there was one, but in the dropdown menu on a note, both vertical and horizontal split have the same icon — the one for a vertical split. The horizontal split icon should be different and, well, horizontal.
![2021-12-11 07_08_08-inbox - Obsidian v0 13 7](https://user-images.githubusercontent.com/5279653/145667906-489ee076-892a-42ed-abdd-944819b36a8d.jpg)

**Comment by ceciliamay** [comment]
Fixed by the amazing @crashmoney ! Again, thank you so much for your contribution!! ✨💖
