### ISSUE TITLE
WYSIWYG editor issues

### ISSUE THREAD

**Issue by whippingdot** [ceciliamay/obsidianmd-theme-primary#33]
With the new editor being released, I think some issues have popped up:
1. For some reason there is more color in the syntax highlighting of latex stuff I think. Before the update, I am pretty sure there was NO syntax highlighting. If you added these in yourself then please at least change the colors to fit the current color scheme.
![image](https://user-images.githubusercontent.com/64354499/147018047-93a15dcb-d94a-44a8-a9f2-f50bec8cb090.png)

2. The color of links look different in both the reading mode and the editing mode in WYSIWYG (there are two different modes).
Reading:
![image](https://user-images.githubusercontent.com/64354499/147018335-4a421005-9b43-4d9d-bcb9-6012ff11c39a.png)

Editing:
![image](https://user-images.githubusercontent.com/64354499/147018292-932edfa7-4ccc-4c6e-af69-0a6e3d3749d4.png)

I just opened up obsidian and found these errors, so if I find any more errors in the future (which there probably are because of the big update) then I will report them in this issue thread!

**Comment by ceciliamay** [comment]
Thank you so much for reporting these issues!! There will definitely be tons since I'm not an Insider and haven't updated the theme to support LP, so I'll add all of these to the next mega update coming. Both 1 and 2 are definitely issues unintended. I'll work on them soon and again, thank you so much for letting me know!! Waiting for more issues to be reported 😄

**Comment by whippingdot** [comment]
I am also not an insider - the update just released for everyone!

**Comment by ceciliamay** [comment]
Active Line not working as intended in new Live Preview. Active Line CSS class has been changed to `.cm-active`. See [this official guide](https://publish.obsidian.md/hub/04+-+Guides%2C+Workflows%2C+%26+Courses/Guides/How+to+update+your+plugins+and+CSS+for+live+preview)

**Comment by whippingdot** [comment]
![image](https://user-images.githubusercontent.com/64354499/147447369-cfe3dee0-5cc1-4daf-a732-003bcddd076e.png)
Here are more mistakes for you:
![image](https://user-images.githubusercontent.com/64354499/147447482-eb94b967-f967-4503-80e4-6aae0f4d4982.png)
![image](https://user-images.githubusercontent.com/64354499/147447503-668e7b2e-41bf-42fe-b1ee-a06c05d6b598.png)


I don't know what are mistakes and what are not so I hope you can identify that!

In links, the first one is a wikilink which has plain text, the second is a link to example.com, and the third is a link to another document in my vault

**Comment by ceciliamay** [comment]
Hey!! I hope you are still enjoying Primary. It's now at v.1.0 - releasing a mega update with tons of fixes, including full v.0.13+ support!! ✨🥳 Please update your theme and check it out! [Here's the changelog.](https://github.com/ceciliamay/obsidianmd-theme-primary/releases/tag/v.1.0.0)

**Comment by whippingdot** [comment]
Okay!
