### ISSUE TITLE
Status bar interference

### ISSUE THREAD

**Issue by miharekar** [ceciliamay/obsidianmd-theme-primary#34]
Status bar floats above right pane/content making it impossible to click "behind" it.

<img width="435" alt="CleanShot 2021-12-25 at 12 35 46" src="https://user-images.githubusercontent.com/986645/147384116-05ca7770-5a7b-4f23-94fa-165cce56d6ec.png">

Probably it should "stick" to the left edge of the right pane. You can scroll the content down further, or add an enter or two if needs be, but it's impossible to scroll the right pane further.

**Comment by ceciliamay** [comment]
No more status bar interference with v.1.0!! Please update your theme and check it out! [Here's the changelog.](https://github.com/ceciliamay/obsidianmd-theme-primary/releases/tag/v.1.0.0)

**Comment by miharekar** [comment]
Awesome, thank you @ceciliamay 🥰
