### ISSUE TITLE
Custom checkboxes

### ISSUE THREAD

**Issue by ScottKillen** [ceciliamay/obsidianmd-theme-primary#35]
This is a beautiful theme!

Would you consider adding another feature that aids visual organization? Custom checkboxes? See #4 [here.](https://github.com/jdanielmourao/obsidian-sanctum/blob/main/documentation/Theme_Guide.md)

![image](https://user-images.githubusercontent.com/1509989/147641941-271470d1-e030-4140-9718-61dad1def2db.png)

**Comment by eleanorkonik** [comment]
"upvoting" this because I rely on these a lot 🙈

**Comment by rivrwind** [comment]
Upvoted

**Comment by eleanorkonik** [comment]
> Upvoted, might try and pull the code from Sanctum and do it myself

Here's the snippet: https://github.com/jdanielmourao/obsidian-sanctum/blob/eb25c4de5d82440f8be7e52dc6c23e918e39abce/snippets/Sanctum%20Custom%20Checkboxes.css

I haven't been able to get the strikethrough to go away when using it for Primary, but I also have not tried very hard to be honest.

**Comment by ceciliamay** [comment]
I finally added a bunch of alternative checkboxes! Please read the [full changelog here](https://github.com/ceciliamay/obsidianmd-theme-primary/releases/tag/v.1.3.0) to know the syntax! 🥳🎉 Please let me know what you think.
