### ISSUE TITLE
[Feature request] Switch to fonts with wider international characters support (e.g. Cyrillic)

### ISSUE THREAD

**Issue by dsent** [ceciliamay/obsidianmd-theme-primary#36]
A picture is worth a thousand words:
![image](https://user-images.githubusercontent.com/8774536/147732283-572e96a0-29b5-411c-8e06-fb0463ffac7d.png)
(no Cyrillic characters in the heading font, so a substitute font is used)

P.S. The theme is **awesome**.

**Comment by ceciliamay** [comment]
Hello there! [Style Settings is now available for Primary on v1.2](https://github.com/ceciliamay/obsidianmd-theme-primary/releases/tag/v.1.2.0)! I added different preset fonts you can choose from and the ability to choose your own font. Let me know how it's looking!!

**Comment by dsent** [comment]
A really nice selection of fonts, thank you! Lora, Inter, and Roboto support Cyrillic.
