### ISSUE TITLE
two Panes side by side open the same time for edit

### ISSUE THREAD

**Issue by godwolfi** [ceciliamay/obsidianmd-theme-primary#37]
Hello Cecilia.
First, thank you for the beautiful theme you have created.
Since then, I enjoy working with Obsidian even more.
One feature I would still like is to be able to see/edit two "panes" side by side at the same time. How can I set this up? The "split function" always opens a panel only in full screen mode. Thank you in advance for your answer. 
Kind regards Wolfgang

**Comment by ceciliamay** [comment]
Hello there Wolfgang!! Thank you so so much for the kind words!!

I'm not sure if there is an issue here - I always have 2 notes open (always, all the time) and an occasional 3rd one. I set this up by `Ctrl` + Clicking on the desired note for the next pane. I don't experience anything like you've said - a panel opening up only in full screen mode. 🤔

![image](https://user-images.githubusercontent.com/90643719/147753583-b5611839-89f9-461a-a480-343fd3db1c02.png)

This might be an app problem and not a theme problem? If issues persist, I'd love to see maybe a gif or video on what's going on on your end so I could better assist you!

 Some suggestions:
- Relaunch Obsidian/Restart your computer
- Check all plugins one by one in case any plugin is causing the problem
- Check if it occurs with other themes 
- Safely reinstall Obsidian
- Check the forums? 🥲

**Comment by godwolfi** [comment]
Hi Cecilia,
thank´s for your fast response.

I send you a picture how it looks on my system (mac os, newest version, also obsidion with newest version):
![Obsidian Pane Demo](https://user-images.githubusercontent.com/96865222/147755735-dd643388-3fac-4bb7-a23c-8f1b2ba5ae69.jpg)
I have to check the rest of what you wrote.
With normal Pane, it´s going. With Sliding Pane it doesnt going.

**Comment by godwolfi** [comment]
and with the Cybertron Theme it´s also going. Not Perfekt, you see it on the right Side of my Screenshot. The Text is not in the middle of the pane. But i can live with this
![Osidian Cybertron Theme](https://user-images.githubusercontent.com/96865222/147756808-59432fcd-abf3-46f9-9584-30a426ffd98e.jpg)
.

**Comment by ChrisBarfod** [comment]
This is due to the Sliding Panes plugin. Toggle leaf auto width to alternate between the 2 layouts.

**Comment by godwolfi** [comment]
Hello Chris.
great, thank you for the tip! That is the solution. So simple!

**Comment by ceciliamay** [comment]
Thanks for the help @ChrisBarfod !!! ✨💖🎊🎉 I'll be closing this!!
