### ISSUE TITLE
The "Search current file" input box blocks the first line of the active note

### ISSUE THREAD

**Issue by SkepticMystic** [ceciliamay/obsidianmd-theme-primary#40]
Line `1` is blocked by the search bar

![image](https://user-images.githubusercontent.com/70717676/147882660-fe7b3b72-9caf-444a-a1d8-d4a7710adf9a.png)

**Comment by ceciliamay** [comment]
I don't think I have repositioned the search bar at top 🤔 - I can't replicate the issue because mine is at the bottom and I definitely don't have any snippets 🤔 Could you check again, after some restarts maybe, if this is still occurring?

**Comment by SkepticMystic** [comment]
Hahaha how strange! I reloaded and it still happens. I'm working in a test vault with no other css snippets, so it's not that...

**Comment by SkepticMystic** [comment]
Yeah, and on the default theme, it goes back to the bottom

**Comment by ceciliamay** [comment]
yep - definitely did not reposition anything in the css 🤔 
my current version is v13.14 - no insider, are you by any chance using insider?

**Comment by SkepticMystic** [comment]
I am using insider, yes `0.13.17`. Must be to do with that!

**Comment by ceciliamay** [comment]
I suppose so! I'll see what I can do if this still occurs once the build goes public . I'll be sure to fix it ASAP by then 😄 Thank you so much for reporting!!

**Comment by ceciliamay** [comment]
Hey!! I hope y'all are still enjoying Primary. This issue is now fixed in the new update at v.1.0 - releasing a mega update with tons of fixes, including full v.0.13+ support!! ✨🥳 Please update your theme and check it out! [Here's the changelog.](https://github.com/ceciliamay/obsidianmd-theme-primary/releases/tag/v.1.0.0)
