### ISSUE TITLE
Fold indicators are displayed incorrectly in Obsidian 0.3.19

### ISSUE THREAD

**Issue by dsent** [ceciliamay/obsidianmd-theme-primary#42]
In 0.3.18 they were moved closer to the headings (see [changelog](https://forum.obsidian.md/t/obsidian-release-v0-13-18-insider-build/29790)). In Primary, they're still displayed as they were previously, but you have to click to the right of the displayed indicator to actually fold/unfold stuff.
![image](https://user-images.githubusercontent.com/8774536/148386706-6ae964d6-ea6c-481f-8b48-a66126a27366.png)

**Comment by dsent** [comment]
The fold indicators for the front matter section is displayed correctly:

**Comment by dsent** [comment]
(offtop: #42 get, yay!)

**Comment by rivrwind** [comment]
I fixed this on my end with

```
.cm-fold-indicator{
    font-size: 1em !important;
}
```

**Comment by rivrwind** [comment]
I fixed this on my end with
```
.cm-fold-indicator{
    font-size: 1em !important;
}
```

**Comment by ceciliamay** [comment]
Forgot to update this one - this has also been fixed in v.1.0! [Changelog.](https://github.com/ceciliamay/obsidianmd-theme-primary/releases/tag/v.1.0.0)
