### ISSUE TITLE
multiple and very fat underscores with links in headings

### ISSUE THREAD

**Issue by gardssh** [ceciliamay/obsidianmd-theme-primary#46]
Hi, first, I love the theme! The only thing I find a bit annoying, and wasn't able to fix myself is the (in my opinion of course) a bit too much underscores on links in headers. 

<img width="629" alt="Screenshot 2022-01-13 at 22 07 55" src="https://user-images.githubusercontent.com/71121216/149416716-57bf0f5a-5a76-4934-b0ad-55511902a55b.png">

**Comment by ceciliamay** [comment]
This is definitely not how it should look like ehehe 😅 (see legacy editor version).

I'm currently fixing this and will come in the next update (should fix all LP problems!!) Thank you reporting and I'm glad you're enjoying it (except for the double border parts 😆)!!!

**Comment by ceciliamay** [comment]
Hey!! I hope y'all are still enjoying Primary. It's now at v.1.0 - releasing a mega update with tons of fixes, including full v.0.13+ support!! ✨🥳 Please update your theme and check it out! [Here's the changelog.](https://github.com/ceciliamay/obsidianmd-theme-primary/releases/tag/v.1.0.0)
