### ISSUE TITLE
icons and text overlaps

### ISSUE THREAD

**Issue by gardssh** [ceciliamay/obsidianmd-theme-primary#48]
Love that you updated the theme, every problem I had before is fixed (as I can think of). 
Buuuut got a new one.
When I search for a note the icon for "create this note" overlaps with the text.

<img width="79" alt="Screenshot 2022-01-25 at 19 52 05" src="https://user-images.githubusercontent.com/71121216/151049459-35d6eaf9-3116-4a42-a52b-3a8e3d7bad6b.png">

**Comment by HEmile** [comment]
This is probably the same issue, but it also happens for aliases:
![image](https://user-images.githubusercontent.com/1289165/151137463-38b8417c-b467-40ba-8920-637d590cf7c4.png)

**Comment by ceciliamay** [comment]
This has been fixed in [Release v.1.1](https://github.com/ceciliamay/obsidianmd-theme-primary/releases/tag/v.1.1.0)!! Please update your themes 😄 Thanks for reporting!!

**Comment by maxhot** [comment]
> This has been fixed in [Release v.1.1](https://github.com/ceciliamay/obsidianmd-theme-primary/releases/tag/v.1.1.0)!! Please update your themes 😄 Thanks for reporting!!

Much appreciated. Looks great!
