### ISSUE TITLE
the icon of pinned commands overlaps the title

### ISSUE THREAD

**Issue by oxdc** [ceciliamay/obsidianmd-theme-primary#49]
![image](https://user-images.githubusercontent.com/29519076/151096814-012919d8-4db4-4b43-a20d-a1b40a5197a8.png)

**Comment by ceciliamay** [comment]
i didn't know you could pin commands 👀 how did you do it so i could replicate this issue? i do think it's related to #48 - which will be fixed shortly ;)

**Comment by oxdc** [comment]
![image](https://user-images.githubusercontent.com/29519076/151133982-490fb770-1a31-4459-affb-2b857c71a959.png)

1. Open the options of "command palette";
2. Select a command in the dropdown list;
3. It will appear in the "pinned commands".

**Comment by oxdc** [comment]
```diff
  .modal-container .suggestion-item {
    font-size: var(--font-scale-1);
    line-height: var(--line-height-0-5);
    padding: var(--scale-2-3)
             var(--scale-2-1)
             var(--scale-2-3)
-            var(--scale-8-2);
+            var(--scale-8-4);
    border-radius: var(--scale-2-2);
    border: 1px solid transparent;
  }
```

**Comment by ceciliamay** [comment]
Fixed this in [v.1.1](https://github.com/ceciliamay/obsidianmd-theme-primary/releases/tag/v.1.1.0)! Please update! ✨
