### ISSUE TITLE
Don't hide checkboxes

### ISSUE THREAD

**Issue by SkepticMystic** [ceciliamay/obsidianmd-theme-primary#5]
Alot of themes do this, and I'm not sure exactly which rule is making it happen. But checkboxes often get shrunk down to a few pixels:
![image](https://user-images.githubusercontent.com/70717676/139833685-8f4be2fa-ed70-4456-8744-8ffad68bba1b.png)

**Comment by SkepticMystic** [comment]
Ahh, it's these two styles. When toggled off, checkboxes show:

![image](https://user-images.githubusercontent.com/70717676/139834642-8af1e2a5-be1c-4a82-8176-5214082f2350.png)

**Comment by OfficerHalf** [comment]
This is usually done to create a checkbox element that looks the same between browsers and is themable. It looks like something went wrong with these:
![image](https://user-images.githubusercontent.com/4851889/139920221-74d4a842-8c6b-40d4-a5d1-79791ef1ab95.png)

**Comment by ceciliamay** [comment]
Thanks for flagging this guys! If I remove `-webkit-appearance: none` and `appearance: none`, it removes the styling and resorts to a default style:

![checkbox style without webkit-appearance/appearance properties](https://user-images.githubusercontent.com/90643719/140601144-6ce2abb8-d3fe-4244-b502-6da1c2040382.png)

I'm considering @OfficerHalf 's suggestion to broaden the styling to affect the whole app. To better support the styling of the checkboxes, I'd love to know where you guys found these issues. Is it in Preview Mode? Is it a plugin - and if so what plugin? How may I replicate these issues you're encountering? Hoping to hear your feedbacks soon and other ideas are certainly welcome 😄

**Comment by OfficerHalf** [comment]
I saw this in my own plugin, Obsidian Trello, on a card that had a checklist. Not the easiest one to replicate with since it requires some setup 😅 I'd bet this happens in one of the task plugins as well.

**Comment by ceciliamay** [comment]
This has been fixed in [Release v.0.1.1](https://github.com/ceciliamay/obsidianmd-theme-primary/releases/tag/v0.1.1)! 🎉 I actually took the time to setup an Obsidian Trello myself to replicate this, so it should be working especially for that plugin! Let me know if any is still experiencing issues with the checkboxes 😄
