### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by whippingdot** [ceciliamay/obsidianmd-theme-primary#50]
Comments are broken...or maybe this isn't a comment?:
![image](https://user-images.githubusercontent.com/64354499/151125466-f134696f-f6a3-4595-8504-be6e18135076.png)

**Comment by ceciliamay** [comment]
o Co
I am not sure if that is a comment...? The comments look like these on my end:
![image](https://user-images.githubusercontent.com/90643719/151153306-7974fcb5-ab19-4399-9b62-fc2c38f25b73.png)
![image](https://user-images.githubusercontent.com/90643719/151153330-971f65b0-5a45-4c4f-8b28-702acf3484eb.png)

Can you send me the contents so I can check it out on my end?

**Comment by whippingdot** [comment]
Hmm yea fine.

```markdown
# Album - Artist Name

## Songs

1. Song 1: {Review}/10
2. Song 2: {Review}/10
3. Song 3: {Review}/10

### Remarks



## Final Score

After averaging out all the scores, the album ranks at a solid (rounded to the nearest tenths place):
$$$$
%%
## Deluxe

1. Song 1: {Review}/10
2. Song 2: {Review}/10
3. Song 3: {Review}/10

### Remarks



## Overall Remarks



## Relations

%%
```

This is a song review template i made. In editing mode it is perfectly fine, like on your end, but on read mode it gets the error message...

I am using the WYSIWYG editor btw

**Comment by ceciliamay** [comment]
So I checked your note and it looks to be a template issue 👀 Here's the template using Obsidian's default theme, and Minimal:

![image](https://user-images.githubusercontent.com/90643719/151222172-3293549f-912e-4497-a551-128e86909c25.png)
![image](https://user-images.githubusercontent.com/90643719/151222274-56f8872e-4fde-45d8-a2a5-add60ffb88b7.png)
![image](https://user-images.githubusercontent.com/90643719/151222310-a16551d7-a0d0-4325-bc7d-ce0f072d5d8b.png)

If I remove all of the heading formatting (#'s) I don't get the issue anymore. 😕

**Comment by whippingdot** [comment]
Oh okay. Is there no fix to this? I dont' really need one but just asking.

**Comment by ceciliamay** [comment]
Okay I think I got it. The issue is caused by the

**Comment by whippingdot** [comment]
Thank you so much!  I will add something into the math block to make the error not come anymore!
