### ISSUE TITLE
unexpected padding for inline code within links

### ISSUE THREAD

**Issue by oxdc** [ceciliamay/obsidianmd-theme-primary#52]
Note that the underline is either "broken" or covered.

Editor:
![image](https://user-images.githubusercontent.com/29519076/151158423-a0c10f72-8d75-4498-ac71-a934bfe5f12c.png)

Preview:
![image](https://user-images.githubusercontent.com/29519076/151158469-8f5e4201-455f-42f4-a74f-da73fd871a20.png)

**Comment by ceciliamay** [comment]
I think I fixed this issue along with another fix I did for the links for Release [v.1.1](https://github.com/ceciliamay/obsidianmd-theme-primary/releases/tag/v.1.1.0)! Could you update your theme, check it out and let me know how it's looking?

**Comment by oxdc** [comment]
![image](https://user-images.githubusercontent.com/29519076/152340421-b012ca1d-2324-402e-90ee-86de7686d397.png)

![image](https://user-images.githubusercontent.com/29519076/152340791-234eabb1-f00f-47b6-8222-786b486eba53.png)

It works fine now, but the text color of inline code is overridden by `.cm-link` in live preview mode.

**Comment by ceciliamay** [comment]
Okay! Pushed a final fix for this one. It's now consistent across the board! Update it one more time and let me know if it's working on your end!!

**Comment by oxdc** [comment]
Thanks! It works now.
