### ISSUE TITLE
Checkboxes for Tasks plugin are slightly cut in Live Preview

### ISSUE THREAD

**Issue by eatmoresushi** [ceciliamay/obsidianmd-theme-primary#53]
The checkboxes in the [Tasks](https://github.com/schemar/obsidian-tasks) plugin, as shown below couldn't show in full for both checked and unchecked in Live Preview mode (Editing mode):

![CleanShot 2022-01-26 at 23 21 52](https://user-images.githubusercontent.com/7425685/151162123-f8ad1a34-c873-46b4-84e9-afd116d7c919.png)

![CleanShot 2022-01-26 at 23 22 36](https://user-images.githubusercontent.com/7425685/151162201-cedd84ca-047b-45fb-baad-748c6d8a5bab.png)

In Preview mode, they both show fine:
![CleanShot 2022-01-26 at 23 23 53](https://user-images.githubusercontent.com/7425685/151162402-960ba91e-a898-4ffb-b1cf-e1a70aa01858.png)
![CleanShot 2022-01-26 at 23 24 04](https://user-images.githubusercontent.com/7425685/151162421-5b047f24-6981-4fa8-a7d5-e9e64f1af76b.png)

**Comment by ceciliamay** [comment]
Hmmm.. I can't seem to replicate this on my end... I've installed the Tasks plugin and created a task just to check. It's working for both Live Preview and Preview Mode for me. Could you try updating the theme 2-3x and see if it's fixed? If it's still not fixed after updating, can you show me how maybe with a .gif or a sequence of screenshots how this plugin works? I might've missed something. Let me know soon and so I can brew a solution for ya!

**Comment by eatmoresushi** [comment]
Hi, thank you so much for the reply. I tried to make a gif:

![primary_tasks](https://user-images.githubusercontent.com/7425685/152445181-714b03f9-927b-4b71-a8bc-09063ac36814.gif)

The checkbox inside the tasks code block is cut slightly on the left.

**Comment by ceciliamay** [comment]
Sorry for the late follow up on this @eatmoresushi . I've recently did some some changes to the checkboxes. Can you check if the checkboxes no longer get cut off?

This is the expected result:
![image](https://user-images.githubusercontent.com/90643719/159172370-dc7fce32-5379-4f4e-9471-645570556902.png)
![image](https://user-images.githubusercontent.com/90643719/159172394-228c2645-7d51-4410-8190-578783e1db8f.png)

**Comment by eatmoresushi** [comment]
Hi, thanks for the update. Just revisited your theme and it's even better! You are doing an amazing job. As for the issue, it seems I still have it. The checkbox is getting cut a little bit on the left. It should be fine might be some problems with my computer.

**Comment by ceciliamay** [comment]
got it! i'll close this for now. 😄 @eatmoresushi quick q - what operating system are you on? are you on mac or windows? I used to encounter some problems with how checkboxes render between those 2 OS 👀 - wanted to see if this was related

**Comment by eatmoresushi** [comment]
@ceciliamay I'm using macOS 12.3
