### ISSUE TITLE
Numbered list goes to 9 and restarts in 0

### ISSUE THREAD

**Issue by Arthurit0** [ceciliamay/obsidianmd-theme-primary#54]
Well, the title is kinda of self explanatory: numbered lists only go up to 9 elements and then the list resets, starting in 0.

![numbered list bug](https://user-images.githubusercontent.com/57883830/151216751-de47c1b1-f33d-4b75-8c5d-5ec0630d154a.png)

**Comment by ceciliamay** [comment]
Thank you so much for reporting this!! Unfortunately, it's not replicating on my end, and it seems to work like it should 👀
I checked it for both Live Preview, Source View, Preview View and even with the Legacy editor. Could you try updating the theme one more time to see if this would fix it? If it still doesn't work, maybe try remove and installing the theme again. Let me know if any of these work!

Here's how it look on my end:
![image](https://user-images.githubusercontent.com/90643719/151228245-25972568-d6ea-48be-8d90-3640bfc639de.png)
![image](https://user-images.githubusercontent.com/90643719/151228339-dc09c6fa-8e5c-4ab0-b5df-5d38e12555f5.png)
