### ISSUE TITLE
Text in Links Will Break to Wrap Lines in Reading View

### ISSUE THREAD

**Issue by Signynt** [ceciliamay/obsidianmd-theme-primary#56]
The text in Links will be broken in the middle of a word to wrap lines, which makes reading them hard, and is not consistent with wrapping in regular text. This doesn't happen in Editing Mode, where the text wraps correctly, and identical to how regular text wraps. The below screenshots should demonstrate this clearly.

**Reading View**:
![image](https://user-images.githubusercontent.com/67801159/151535911-0bfe6c39-5dee-4f1d-9939-323848317ab8.png)

**Editing View**:
![image](https://user-images.githubusercontent.com/67801159/151536002-b536d2eb-8089-4453-aa00-fd3e1648967c.png)

Here's the text I used for testing purposes:

```
A long sentence that will cause links to wrap in `Reading View`, which makes reading [[M. obturatorius internus]] harder

A long sentence that will cause links to wrap in `Reading View`, which makes reading M. obturatorius internus harder

Another example sentence that will cause links to wrap sentence that will cause links [[Dreiblättrige Keimscheibe]] to wrap

Another example sentence that will cause links to wrap sentence that will cause links Dreiblättrige Keimscheibe to wrap
```

**Comment by ceciliamay** [comment]
Oops! I misplaced a property. Will send out an update early next week! Thanks for reporting 😄

**Comment by ryadaj** [comment]
Thanks for the beautiful theme and responsive updates :)

I'm new to Git so I'm not sure if adding to this issue is kosher, but this is happening in Editing View as well
![Screen Shot 2022-02-02 at 08 05 28](https://user-images.githubusercontent.com/82765301/152159454-d4f020fb-31ea-4823-8f88-ae4a5088ddcc.png)

**Comment by ceciliamay** [comment]
Fixed this in [v.1.1](https://github.com/ceciliamay/obsidianmd-theme-primary/releases/tag/v.1.1.0)! Please update! ✨
