### ISSUE TITLE
Bullet Points Should Be Displayed Identically in Reading and Editing View

### ISSUE THREAD

**Issue by Signynt** [ceciliamay/obsidianmd-theme-primary#57]
It would provide better visual parity for bullet points to be formated the same, no matter which view is currently being used. (I'm refering to the little dot used by the bullet points.)

The way it's rendered is visually easier to differentiate in the Reading View, however if it is a limitation of Editing View that all the bullet points need to look the same, it would be a worthwhile compromise to change the Reading View to match the Editing View in my opinion. 

**Reading View**:
![image](https://user-images.githubusercontent.com/67801159/151577143-b55f4e9a-dd2e-4fa4-bc66-52bab163174c.png)

**Editing View**:
![image](https://user-images.githubusercontent.com/67801159/151577457-38366967-2fed-4c53-ae07-66a2ff0604e4.png)

**Comment by ceciliamay** [comment]
Awww I love the bullet points in Preview - but I totally resonate with your opinion!! I'll try and see if there's a hack I could do with it... if not - then of course I'll resort to bullets by end of month. Thanks for bringing this to light!
