### ISSUE TITLE
Misaligned "Create Note" Icon in Quick Switcher

### ISSUE THREAD

**Issue by Signynt** [ceciliamay/obsidianmd-theme-primary#58]
![image](https://user-images.githubusercontent.com/67801159/151581288-4ed59b93-e15f-4f43-b57d-b061ddb7bb69.png)

**Comment by maxhot** [comment]
Looks like duplicate of #48

**Comment by ceciliamay** [comment]
This will be fixed early next week!! Hold on guys ;)

**Comment by Signynt** [comment]
Oops, didn't see that issue!

**Comment by ceciliamay** [comment]
Fixed this in [v.1.1](https://github.com/ceciliamay/obsidianmd-theme-primary/releases/tag/v.1.1.0)! Please update! ✨
