### ISSUE TITLE
Default button styling

### ISSUE THREAD

**Issue by OfficerHalf** [ceciliamay/obsidianmd-theme-primary#6]
Looks like buttons without some sort of class applied aren't getting completely styled, and are still getting `background-color: var(--interactive-normal)`, which I don't think your theme has replaced, so the button just looks really out of place:

![image](https://user-images.githubusercontent.com/4851889/139920642-dd4bc33d-13f9-4d2e-9ef7-a8b055488772.png)

This isn't a big deal; as far as I know buttons are only used in the main app inside modals, and those are styled. But plugins are wily and add them other places.

**Comment by ceciliamay** [comment]
I'd love for you to use the cute buttons I made though 😭

That specific "Manage" button (and other CTA buttons) is supposed to look like this:
![image](https://user-images.githubusercontent.com/90643719/140601681-fea0a891-04bd-402f-86e9-ea9cc4c8f051.png)

But general buttons in Dark Mode are supposed to look like this:
![image](https://user-images.githubusercontent.com/90643719/140601707-9ca604a3-3dc5-4ab7-830b-dc8bed111326.png)

I feel that something else is overriding the style. Can I get a list of all the plugins you're using? I want to replicate the issue on my end and see if I can get it fixed 😄

**Comment by OfficerHalf** [comment]
Yeah, sorry that screenshot was a poor example. That was me playing in the devtools attempting to figure out why the buttons in my Trello plugin didn't look right. I see this again in my Trello plugin:

![image](https://user-images.githubusercontent.com/4851889/140608720-11c89e71-9d64-41bd-8a27-4f4886233156.png)

My plugin doesn't add any styles to the button it just plops it there with no class as a `<button type="button"></button>`

**Comment by ceciliamay** [comment]
This has been fixed in [Release v.0.1.1](https://github.com/ceciliamay/obsidianmd-theme-primary/releases/tag/v0.1.1)! 🎉 Thank you so much for letting me know of this issue! Cute buttons FTW!! 😆
