### ISSUE TITLE
Remove the blinking of text while Obsidian is loading [Tiny Fix]

### ISSUE THREAD

**Issue by Signynt** [ceciliamay/obsidianmd-theme-primary#67]
When Obsidian is loading, and is saying `Loading Plugins`, `Loading Workspace` etc. that text will blink. At the same time the loading bar is moving fast, causing a very hectic look, which visually doesn't really match the rest of the theme, which is more calm and comfortable.
I understand that it is important to communicate that "something is happening" and that the loading isn't stuck, but the loading bar is already indicating that, so hectic blinking text isn't really necessary to indicate this. I'd propose that this text could be made static to calm things down a bit.

This issue isn't as much an issue on desktop, where Obsidian loads pretty quickly, but on Android where it loads for a while this is pretty jarring. (I've heard that the long loading times have been reduced in the latest insider on Android though).

**Comment by ceciliamay** [comment]
I changed how this looked like in v1.2! Check it out and let me know what you think. [Here's the changelog.](https://github.com/ceciliamay/obsidianmd-theme-primary/releases/tag/v.1.2.0)
