### ISSUE TITLE
Smaller Tab Icons

### ISSUE THREAD

**Issue by DasCapschen** [ceciliamay/obsidianmd-theme-primary#68]
Firstly, thanks for the theme, I love it ❤️ 

The only thing I'm not really a fan of right now, is how big the header icons in the sidebar are.   
I think this should be a style setting to reduce their size.

Something like this 
big icons (34x36): 
![header_icons_primary](https://user-images.githubusercontent.com/3923406/153753020-2d5950c8-9176-4cb0-8bcc-5e866843e25f.png)

small icons (24x26): (I know, the icon isn't centered anymore, I'm a css noob 🙈)
Reduces the overall size of the header by 10 pixels.
![grafik](https://user-images.githubusercontent.com/3923406/153753131-9dc95a6e-590e-4761-80d5-cfecaa752430.png)

compare with minimal theme: 
![header_icons_minimal](https://user-images.githubusercontent.com/3923406/153753044-bd7408c6-7ea2-4ea3-9cdb-04b185f40a05.png)

**Comment by tyindeepit** [comment]
I agree with having ability to adjust this in style setting. However, I prefer the current design because it fits well with the overall design direction, easy to see, and easy to click. Minimal theme, to me, is quite small and too "two-tone" that it looks flat and a bit inconspicuous.

**Comment by DasCapschen** [comment]
Amazing, thank you. ❤️

**Comment by ceciliamay** [comment]
I hope the options are good enough! Please let me know what you think!

**Comment by DasCapschen** [comment]
Yes, I think the options are great! It's amazing that you made both size and design (minimal / original) settings :)
Thank you very much!
