### ISSUE TITLE
Dataview table fix

### ISSUE THREAD

**Issue by miharekar** [ceciliamay/obsidianmd-theme-primary#71]
Hey, love the theme and all the updates you do!

I [scraped my Goodreads data into Obsidian](https://github.com/miharekar/goodreads-scraper-for-obsidian) and ended up with the following table with dataview:

<img width="1016" alt="CleanShot 2022-02-16 at 10 49 12@2x" src="https://user-images.githubusercontent.com/986645/154239576-ba08dda6-8cd7-4617-a727-3ec980c2487e.png">

Some CSS snippet-magic was needed to make it nice:

<img width="972" alt="CleanShot 2022-02-16 at 10 48 55@2x" src="https://user-images.githubusercontent.com/986645/154239626-0bbf315f-2fc2-4aeb-a653-767f2cc1835d.png">

Don't know if it breaks some other dataview integration but if not, you might consider including this:

```
table.dataview {
  word-break: normal;
  overflow-wrap: normal;
}
```

Or something better. I'm no CSS dev, but this did the job 😅

**Comment by ceciliamay** [comment]
Thanks for catching this @miharekar !! I pushed a quick update + tiny release. 🎉🙏
