### ISSUE TITLE
Outline pane indentation is confusing

### ISSUE THREAD

**Issue by alexwiench** [ceciliamay/obsidianmd-theme-primary#72]
I find myself accidentally thinking sibling headings are actually nested due to the spacing in the outline pane. I think headings without children should have extra space on their left side to compensate for the space the arrow takes up. 

This is what it looks like now: 
![primary indentation](https://user-images.githubusercontent.com/2208008/154303604-7f886a48-032a-4e7a-8dd3-852670136c58.png)

And this is what it should look like:
![default indention](https://user-images.githubusercontent.com/2208008/154303644-687103b8-6fab-46c0-9215-98979f5c3603.png)

**Comment by ceciliamay** [comment]
Fixed this in the new update! Read the [full changelog here](https://github.com/ceciliamay/obsidianmd-theme-primary/releases/tag/v.1.3.0)! 🥳🎉
