### ISSUE TITLE
Tags wrap incorrectly

### ISSUE THREAD

**Issue by Signynt** [ceciliamay/obsidianmd-theme-primary#73]
![image](https://user-images.githubusercontent.com/67801159/154328794-1b38f33e-c817-44f7-9657-02dd18469c62.png)
`#anatomie/embryologie #anatomie/eingeweide #anatomie/brusthöhle`

**Comment by hellerbarde** [comment]
I'd like to help. How do I best set up for development? Is there a special way to invoke the Sass compiler? And how can I get it into Obsidian? I will start trying on my own first though.

**Comment by hellerbarde** [comment]
I managed to get started with development, and I think I have a fix, but I would have to test it more. I will create a pull request that I would be appreciative if someone could review.

**Comment by hellerbarde** [comment]
@Signynt Feel free to try out my fix, by the way. You can find the theme file here: https://raw.githubusercontent.com/hellerbarde/obsidianmd-theme-primary/bugfix/tag-line-break/obsidian.css
Copy that into your Obsidian theme folder to try it out. I'd be glad for the feedback.
