### ISSUE TITLE
Make the UI buttons smaller

### ISSUE THREAD

**Issue by rodrigo-rufino** [ceciliamay/obsidianmd-theme-primary#75]
Great theme, but what keeps me from using it more times is the size of the UI buttons. They take so much space on the screen. For example, when I'm with the sidebar open, I need to make it wider in order to show all the buttons. They are so big they are cut out of the sidebar. Example:

![Captura de Tela 2022-02-16 às 19 47 57](https://user-images.githubusercontent.com/18670446/154370532-c1093a36-f2d7-4041-811f-4004b15bfe0a.png)

**Comment by maxhot** [comment]
I actually quite like the large buttons--it makes them easier to target and switch tabs quickly when using a mouse.

I'd hate to see them go. My vote is for an option to toggle between small vs. large buttons.

**Comment by maxhot** [comment]
Makes sense, @rodrigo-rufino.

Sounds like we should wrap the buttons to a new row, regardless of button size, since even smaller buttons could accumulate and outgrow the pane width.

**Comment by ceciliamay** [comment]
@rodrigo-rufino I'm almost done with the customizations! But to ensure usability, I wanted to ask: how many tabs do you use per sidebar?

**Comment by ceciliamay** [comment]
I added style settings for smaller icons and more! Read the [full changelog here](https://github.com/ceciliamay/obsidianmd-theme-primary/releases/tag/v.1.3.0)! 🥳🎉

**Comment by rodrigo-rufino** [comment]
@ceciliamay thank you very much!
