### ISSUE TITLE
Issue with latest insider builds v0.13.25+ img

### ISSUE THREAD

**Issue by miharekar** [ceciliamay/obsidianmd-theme-primary#77]
From the release notes in Discord:

>Theme developers: our new editor has received an upgrade where previous `&ZeroWidthSpace;` characters, used as placeholders for computing cursor positions, have been switched to 0-width `<img>` elements. We recommend double-checking that your theme does not contain global `img { ... }` CSS rules to avoid breaking the editor.

This results in this dark grey rectangles around links and other markdown characters:
<img width="269" alt="CleanShot 2022-02-19 at 12 10 38@2x" src="https://user-images.githubusercontent.com/986645/154798544-dd8931f3-3432-4345-8bd4-3896bc7b988d.png">

which can be fixed by:
<img width="481" alt="CleanShot 2022-02-19 at 12 10 44@2x" src="https://user-images.githubusercontent.com/986645/154798547-274458e0-f47b-4855-8fc6-6f8e92734071.png">

or

```
img.cm-widgetBuffer {
  border: none;
}
```

But, again, there is probably a better way to do it 😅

**Comment by miharekar** [comment]
The discord seems to think this is the best solution:
<img width="874" alt="CleanShot 2022-02-21 at 08 29 01" src="https://user-images.githubusercontent.com/986645/154908363-ea0518ea-92ae-4aa0-9157-ac56ef08400c.png">
<img width="1257" alt="CleanShot 2022-02-21 at 08 29 50" src="https://user-images.githubusercontent.com/986645/154908448-a8dde154-31bb-4e7d-be4a-a39c4ab90228.png">

**Comment by ryadaj** [comment]
Is it just me or have headers also shrunk?
<img width="1512" alt="Screen Shot 2022-02-21 at 20 50 08" src="https://user-images.githubusercontent.com/82765301/155048553-b37ce7a3-fb2a-4b6d-aee0-08227b9bd37b.png">

**Comment by miharekar** [comment]
```
# header 1
some text
## header 2
some text
### header 3
some text
#### header 4
some text
##### header 5
some text
```
generates this 
<img width="268" alt="CleanShot 2022-02-22 at 09 16 28" src="https://user-images.githubusercontent.com/986645/155090603-5a321344-6788-44dd-a6c9-492bc2d23336.png">
so I think it's ok?

**Comment by ryadaj** [comment]
Weird.. for me it is as I showed.

However, I haven't implemented the solution to the grey box issue you note above (I am not savvy enough), so perhaps they are related.

**Comment by ceciliamay** [comment]
Update will come in a bit!

Curious for Mac users with the Insider build: are you getting native scrollbars? or are you getting the obsidian default theme scrollbars?

**Comment by miharekar** [comment]
This is the default:
<img width="142" alt="CleanShot 2022-02-23 at 10 50 20" src="https://user-images.githubusercontent.com/986645/155295709-254df1c6-7975-48dd-95aa-27b25ccaa551.png">
This is with the style setting as Mac grabbable:
<img width="134" alt="CleanShot 2022-02-23 at 10 50 50" src="https://user-images.githubusercontent.com/986645/155295800-adeccfee-0f31-418a-9df9-86900aa9402d.png">

**Comment by ceciliamay** [comment]
Issue Fixed in v.1.2.2!! Please update your theme 🙌 Thanks @miharekar for giving resources!! The convo with Nick and Murf is flawless. 🫂
