### ISSUE TITLE
Issue with headings all being the same size, different spacing

### ISSUE THREAD

**Issue by ryadaj** [ceciliamay/obsidianmd-theme-primary#78]
Thanks for fixing the grey boxes! :)

For me, headings are appearing as the same size and with different spacing. I tried deleting the theme, relaunching obsidian, reapplying the theme, relaunching obsidian, and no success.

<img width="1624" alt="Screen Shot 2022-02-23 at 10 18 35" src="https://user-images.githubusercontent.com/82765301/155349081-05e5ec61-f7af-45c4-81f6-32198c004c8f.png">

**Comment by ceciliamay** [comment]
Okay so I asked around Discord - can you try downloading Obsidian's latest installer and reinstalling Obsidian? koala on Discord mentioned that this might be due to the CSS styling not supported on older chromium versions - which is what the older installers use. Can you try that out and see if it works?

When you do, please don't forget to backup first!

**Comment by ushham** [comment]
This issue was fixed for me by installing the Style Settings community plugin.

**Comment by ryadaj** [comment]
> Okay so I asked around Discord - can you try downloading Obsidian's latest installer and reinstalling Obsidian? koala on Discord mentioned that this might be due to the CSS styling not supported on older chromium versions - which is what the older installers use. Can you try that out and see if it works?
> 
> When you do, please don't forget to backup first!

Thanks! I am an Insider so I am running 0.13.26 which required downloading the installer posted by Licat in the Insider channel. I should have mentioned this from the start, apologies.

Do you think I should reinstall it anyway?

**Comment by ryadaj** [comment]
> This issue was fixed for me by installing the Style Settings community plugin.

This worked!

**Comment by maxhot** [comment]
Enabling Style Settings fixed it for me too. This is a good workaround, but unless we intend for Style Settings to be a permanent dependency, this issue is still a bug (and a regression)

**Comment by ceciliamay** [comment]
Omg - thank you so much for letting me know that installing Style Settings fixed it. I found the issue and I've fixed it. Will push the update after I'm done with some of the other features! Should be out by Sunday. Thanks for the great work everyone!

**Comment by ryadaj** [comment]
Fantastic! You're the best :)

**Comment by ceciliamay** [comment]
Just pushed an update along with some other fixes and features! You can now get rid of Style Settings if you don't want it, and still have the headings be sized as it should be. Read the [full changelog here](https://github.com/ceciliamay/obsidianmd-theme-primary/releases/tag/v.1.3.0)! 🥳🎉
