### ISSUE TITLE
Can't change the font of heading AND body

### ISSUE THREAD

**Issue by Arthurit0** [ceciliamay/obsidianmd-theme-primary#80]
Well, I loved the fonts that were picked for the style settings, but unfortunately I can't change both the header font and the body font, because when I pick one, the other resets.

**When I pick both:**

![image](https://user-images.githubusercontent.com/57883830/155787004-760c730c-aedd-47fd-9490-3f032e627c43.png)

Usually one of them isn't changed at all, but when they are both changed, one of them resets when I reload the page. In both cases, when I open the style settings, one is blank:

![image](https://user-images.githubusercontent.com/57883830/155787682-462b0045-3787-4baf-ab98-6f0e95d45612.png)

And when I change the blank one to a setting, the other resets and opening the style settings again, it is now the blank one:

![image](https://user-images.githubusercontent.com/57883830/155788233-5ad066ff-ff9e-4781-b60e-9e8a286b8c51.png)

Well, this could be a bug of the Style Settings Plugin itself... But I never seen it before with other themes.

**Comment by ceciliamay** [comment]
Fixed this one! It shouldn't have any of the issues :) Read the [full changelog here](https://github.com/ceciliamay/obsidianmd-theme-primary/releases/tag/v.1.3.0)! 🥳🎉

**Comment by Arthurit0** [comment]
It was fixed, thank you! 😁🎉
