### ISSUE TITLE
Please add a style setting to disable primary theme custom checkboxes

### ISSUE THREAD

**Issue by ebullient** [ceciliamay/obsidianmd-theme-primary#81]
Snippetor allows people to generate their own custom css checkboxes, and those can conflict with primary checkbox styles. 

I've structured ebullientworks so that one theme toggle disables theme based task list settings so that snippetor-generated task list snippets work well. 

Would love if you would consider doing this, too.

**Comment by ceciliamay** [comment]
Hey there @ebullient !! So I looked into this, and looks like Snippetor handles specificity really well! The ones I made with Snippetor are the ones for `x` , `>` , `-` and unchecked. I lowered specificity in the new update just in case!

![image](https://user-images.githubusercontent.com/90643719/156930389-e9900959-9bbb-4dee-805a-a211e1a78a2c.png)

I really like Snippetor!! I have some function suggestions:
- adjust border-radius 
- ability to add a custom icon (by using background-image)
  - ability to reposition this custom icon
  - ability to adjust background-size for the custom icon

**Comment by ebullient** [comment]
Border radius adjustment is there already (but it is for all checkboxes.. I have an open issue because the slider doesn't .. slide very well)

You can already add custom icons (somewhat). If you rutn off the color selector, you can specify any valid background string in that field (I should have a zoom-in editor for it, but.. someday). 

https://github.com/ebullient/obsidian-snippetor/discussions/8?converting=1 

You should then already be able to use the positioning sliders to move around where the "box" effectively is.
