### ISSUE TITLE
search bar overlapped by footer

### ISSUE THREAD

**Issue by eleanorkonik** [ceciliamay/obsidianmd-theme-primary#83]
I can't "close" the search bar when I try to find something in a file. 

![image](https://user-images.githubusercontent.com/75856959/156794855-1c5b9202-e400-44f8-9d36-4a7bec09a757.png)

In default theme I can use all the buttons:

![image](https://user-images.githubusercontent.com/75856959/156794959-e523e9e8-d35c-4f24-bd61-2d91209abfc1.png)

**Comment by ceciliamay** [comment]
Thanks for reporting this! Wanted to make sure - is this on Desktop or Mobile (if so, on what device?)

**Comment by eleanorkonik** [comment]
windows 11 desktop

**Comment by ceciliamay** [comment]
I had so much fun fixing this one HAHA! Thanks for posting the issue!! Fixed in [v.1.3.1](https://github.com/ceciliamay/obsidianmd-theme-primary/releases/tag/v.1.3.1)!! 🎉
