### ISSUE TITLE
Increase modal size

### ISSUE THREAD

**Issue by Gnopps** [ceciliamay/obsidianmd-theme-primary#85]
When using the Obsidian tasks-plugin, the modal that opens for editing tasks is too small to show all elements (other themes manage to show all elements). Would it be possible to increase the modal vertical size (or decrease white-space within the modal?) so that the "Apply"-button is always shown?

Modal as it opens:
![image](https://user-images.githubusercontent.com/16313148/157195246-23cd35cc-a79c-4d30-939b-82e979ad35d7.png)

Modal after scroll:
![image](https://user-images.githubusercontent.com/16313148/157195177-f0f7de6e-7a6f-4c51-9e20-6a8c386c9b78.png)

**Comment by ceciliamay** [comment]
I changed the maths for this one! [This is fixed in v.1.4.4!!](https://github.com/ceciliamay/obsidianmd-theme-primary/releases/tag/v.1.4.4) Please update your theme. Thank you for reporting!!
