### ISSUE TITLE
[Suggestion] don't show active focus line background colors in inactive panes

### ISSUE THREAD

**Issue by jsmorabito** [ceciliamay/obsidianmd-theme-primary#9]
This may be a personal preference and I don't know any other apps to model this behavior after, but my thinking is that the active line focus background color is a larger call to attention for the active line than the blinking cursor line and their function is to show the user where they are on the screen (where their cursor is/where their characters will go when they begin typing) at any given moment. Having multiple active focus lines on the screen at one time seems counterintuitive in that way because it splits the attention of the user and makes it harder to distinguish where their active cursor location is.

**Comment by ceciliamay** [comment]
Thank you so much for raising this very fair point!! I have considered this a bug rather than a feature, so it has been the sole fix in this quiet release of [v.0.1.3](https://github.com/ceciliamay/obsidianmd-theme-primary/releases/tag/v0.1.3)!
