### ISSUE TITLE
Bug: Obsidian Map View maps are rastarized by image borders

### ISSUE THREAD

**Issue by HEmile** [ceciliamay/obsidianmd-theme-primary#90]
Hi,

The way Primary styles images means there are borders around the different tiles in Obsidian Map View plugin, creating a weird raster look. Those should be removed for images in that plugin.

**Comment by ceciliamay** [comment]
I've already fixed this and will push the update soon but not gonna lie they look cute - they look like big squarey mahjong pieces

![image](https://user-images.githubusercontent.com/90643719/158290589-0003e3b6-8dde-467f-8df5-e71a2a22605b.png)

HAHAHAA

(it's fixed i promise) -
![image](https://user-images.githubusercontent.com/90643719/158291913-c3a87e02-f6b6-4431-a322-0e4a4aa0685b.png)

**Comment by HEmile** [comment]
Haha, yeah i admit it looked kind of pretty!!
