### ISSUE TITLE
Latest Update Breaks Typewriter Scroll Plugin

### ISSUE THREAD

**Issue by omniaegis** [ceciliamay/obsidianmd-theme-primary#91]
Hi there! Latest updates have since broken the Typewriter Scroll plugin. Seems to only occur with this particular theme. Toggling it on/off doesn't resolve the issue, nor does switching to another theme and then back to Primary. Any idea of what's causing this or rather, if there's an existing workaround?

**Comment by ceciliamay** [comment]
Finally figured what caused this. Please update your theme!! There were a ton bunch of other stuff added in this release - you can read about them [here](https://github.com/ceciliamay/obsidianmd-theme-primary/releases/tag/v.1.4.4). Thank you so much for reporting!!
