### ISSUE TITLE
Checkboxes background

### ISSUE THREAD

**Issue by Gnopps** [ceciliamay/obsidianmd-theme-primary#95]
I think if checkboxes were to have a brighter background would look absolutely fabulous. Currently they look like this:

![image](https://user-images.githubusercontent.com/16313148/159639532-e6300024-b75a-4642-b334-ab7cc009a5fb.png)

And I would suggest something like this (I don't know what looks good at all, just example colour):
![image](https://user-images.githubusercontent.com/16313148/159640147-454e31f2-dfc7-442a-938b-deb275b6ec46.png)

Would it be possible to add a setting or change to make checkbox-backgrounds white(r)?

**Comment by Gnopps** [comment]
I created [this CSS-snippet](https://github.com/Gnopps/ObsidianScripts/blob/main/CheckboxBrightBackground.css) that makes checkboxes stand out more.

**Comment by miharekar** [comment]
I took border color (var(--text-faint)) and made it 98% light.

<img width="357" alt="CleanShot 2022-03-30 at 10 17 45" src="https://user-images.githubusercontent.com/986645/160784998-b8bb6f3d-8e96-419a-9d9d-4d0b8e4e9795.png">

and 10% in dark mode

<img width="352" alt="CleanShot 2022-03-30 at 10 19 30" src="https://user-images.githubusercontent.com/986645/160785355-23eac9e9-2430-4b5a-9d0a-6e0c332c7422.png">

Here's a quick-n-dirty snippet:
```
.task-list-item-checkbox {
  background: hsl(34, 37%, 98%);
}

.theme-dark .task-list-item-checkbox {
  background: hsl(34, 24%, 10%);
}

```

I think it would look much better out of the box.

**Comment by ceciliamay** [comment]
Hey there folks! I added this change natively instead of adding it as customization. Thank you so much for this suggestion because although I initially thought I like the "transparent-like" background checkboxes - I actually liked this more. I really appreciate this!! Thank you guys.💖 [Changelog is here](https://github.com/ceciliamay/obsidianmd-theme-primary/releases/tag/v.1.4.4)
