### ISSUE TITLE
Text and Words not being highlighted when using Ctrl + F

### ISSUE THREAD

**Issue by stone2forge** [ceciliamay/obsidianmd-theme-primary#96]
Whenever I use "Ctrl + F" to find a word, Primary does not highlight the word in question and it gets quite hard to find text or words. Default Theme and Minimal does show a highlight text when using Ctrl + F.

I am currently using Obsidian Insider v0.14.2, Primary Theme v1.4.0 on default settings.

This also occurs on a new vault with nothing added but the theme installed.

![image](https://user-images.githubusercontent.com/76193584/159862984-d181eddb-eeb0-4dbf-a1e8-e9fdd503e97c.png)

**Comment by ceciliamay** [comment]
Hey there! Pushed a quick fix for this one! Thank you so much for reporting. <3
